/* Generated by SLOP transpiler */
#include <sys/socket.h>
#include <unistd.h>
#include <string.h>
#include <arpa/inet.h>
#include <netinet/in.h>

#include "slop_runtime.h"
#include <stdint.h>
#include <stdbool.h>

/* Module: http-server */

/* Forward declarations */
slop_string response_ok(void);
slop_string response_404(void);
int main(void);

/* Return 200 OK with greeting */
slop_string response_ok(void) {
    return SLOP_STR("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nContent-Length: 13\r\nConnection: close\r\n\r\nHello, SLOP!");
}

/* Return 404 Not Found */
slop_string response_404(void) {
    return SLOP_STR("HTTP/1.1 404 Not Found\r\nContent-Type: text/plain\r\nContent-Length: 9\r\nConnection: close\r\n\r\nNot Found");
}

/* Run HTTP server on port 8080 */
int main(void) {
    {
        __auto_type sock = socket(2, 1, 0);
        if ((sock < 0)) {
            printf("%s\n", "Failed to create socket");
            return 1;
        } else {
            {
                slop_arena _arena = slop_arena_new(256);
                slop_arena* arena = &_arena;
                {
                    __auto_type addr = (struct sockaddr_in*)slop_arena_alloc(arena, sizeof(struct sockaddr_in));
                    __auto_type opt = ((int64_t*)((int64_t*)slop_arena_alloc(arena, sizeof(int64_t))));
                    (*opt) = 1;
                    setsockopt(sock, 1, 2, ((void*)(opt)), 4);
                    memset(addr, 0, ((uint64_t)(sizeof(struct sockaddr_in))));
                    addr->sin_family = 2;
                    addr->sin_port = htons(8080);
                    addr->sin_addr.s_addr = 0;
                    if ((bind(sock, ((void*)(addr)), ((uint32_t)(sizeof(struct sockaddr_in)))) < 0)) {
                        printf("%s\n", "Failed to bind");
                        close(sock);
                        return 1;
                    } else {
                        listen(sock, 10);
                        printf("%s\n", "Listening on http://localhost:8080");
                        printf("%s\n", "  GET /health -> 200 OK");
                        printf("%s\n", "  Press Ctrl+C to stop");
                        while (1) {
                            {
                                __auto_type client = accept(sock, NULL, NULL);
                                if ((client >= 0)) {
                                    {
                                        slop_arena _arena = slop_arena_new(4096);
                                        slop_arena* arena = &_arena;
                                        {
                                            __auto_type buf = (uint8_t*)slop_arena_alloc(arena, 4096);
                                            recv(client, buf, 4095, 0);
                                            {
                                                __auto_type resp = (((strstr(buf, (SLOP_STR("GET /health")).data) != NULL)) ? (response_ok()) : (response_404()));
                                                send(client, ((void*)((resp).data)), (resp).len, 0);
                                            }
                                            close(client);
                                        }
                                        slop_arena_free(arena);
                                    }
                                }
                            }
                        }
                        return 0;
                    }
                }
                slop_arena_free(arena);
            }
        }
    }
}
